//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public Donation()
        {
            this.DonationDetails = new HashSet<DonationDetail>();
        }
    
        public int Id { get; set; }
        public string FoodName { get; set; }
        public int ResId { get; set; }
        public int Status { get; set; }
        public System.DateTime Validity { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<DonationDetail> DonationDetails { get; set; }
    }
}
